/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculatePackage;

import javax.swing.JOptionPane;

public class calculate extends javax.swing.JFrame {
    
    double A, B, answer;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(calculate.class.getName());

    /**
     * Creates new form calculate
     */
    public calculate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JlableA = new javax.swing.JLabel();
        JlableB = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        bntAdd = new javax.swing.JButton();
        txtAdd = new javax.swing.JTextField();
        btnSubtract = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        txtSubtract = new javax.swing.JTextField();
        txtMultiply = new javax.swing.JTextField();
        txtDivide = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JlableA.setText("A");
        getContentPane().add(JlableA, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        JlableB.setText("B");
        getContentPane().add(JlableB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 20, -1));

        txtA.addActionListener(this::txtAActionPerformed);
        getContentPane().add(txtA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 90, -1));

        txtB.addActionListener(this::txtBActionPerformed);
        getContentPane().add(txtB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 90, -1));

        bntAdd.setText("A + B =");
        bntAdd.addActionListener(this::bntAddActionPerformed);
        getContentPane().add(bntAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        txtAdd.addActionListener(this::txtAddActionPerformed);
        getContentPane().add(txtAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 80, -1));

        btnSubtract.setText("A - B =");
        btnSubtract.addActionListener(this::btnSubtractActionPerformed);
        getContentPane().add(btnSubtract, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        btnMultiply.setText("A * B =");
        btnMultiply.addActionListener(this::btnMultiplyActionPerformed);
        getContentPane().add(btnMultiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        btnDivide.setText("A / B =");
        btnDivide.addActionListener(this::btnDivideActionPerformed);
        getContentPane().add(btnDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));
        getContentPane().add(txtSubtract, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 80, -1));
        getContentPane().add(txtMultiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 80, -1));
        getContentPane().add(txtDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 80, -1));

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        setBounds(0, 0, 267, 422);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBActionPerformed

    private void txtAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAActionPerformed

    private void txtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddActionPerformed

    private void bntAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAddActionPerformed
    try
    {
        A=Double.parseDouble(txtA.getText());
        B=Double.parseDouble(txtB.getText());
        answer=A+B;
        txtAdd.setText(String.format("%.2f",answer));
    }
    catch(NumberFormatException e)
    {
        JOptionPane.showMessageDialog(calculate.this, "Incorrect number format");
    }
    }//GEN-LAST:event_bntAddActionPerformed

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyActionPerformed
             try
    {
        A=Double.parseDouble(txtA.getText());
        B=Double.parseDouble(txtB.getText());
        answer=A*B;
        txtMultiply.setText(String.format("%.2f",answer));
    }
    catch(NumberFormatException e)
    {
        JOptionPane.showMessageDialog(calculate.this, "Incorrect number format");
    }
    }//GEN-LAST:event_btnMultiplyActionPerformed

    private void btnSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtractActionPerformed
         try
    {
        A=Double.parseDouble(txtA.getText());
        B=Double.parseDouble(txtB.getText());
        answer=A-B;
        txtSubtract.setText(String.format("%.2f",answer));
    }
    catch(NumberFormatException e)
    {
        JOptionPane.showMessageDialog(calculate.this, "Incorrect number format");
    }
    }//GEN-LAST:event_btnSubtractActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
             try
    {
        A=Double.parseDouble(txtA.getText());
        B=Double.parseDouble(txtB.getText());
        answer=A/B;
        txtDivide.setText(String.format("%.2f",answer));
    }
    catch(NumberFormatException e)
    {
        JOptionPane.showMessageDialog(calculate.this, "Incorrect number format");
    }
    }//GEN-LAST:event_btnDivideActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

        txtA.setText("");
        txtB.setText("");
        txtAdd.setText("");
        txtSubtract.setText("");
        txtMultiply.setText("");
        txtDivide.setText("");
        
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new calculate().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlableA;
    private javax.swing.JLabel JlableB;
    private javax.swing.JButton bntAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnSubtract;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtAdd;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtDivide;
    private javax.swing.JTextField txtMultiply;
    private javax.swing.JTextField txtSubtract;
    // End of variables declaration//GEN-END:variables
}
